package org.fireflow.engine.impl;

// Generated Feb 23, 2008 12:04:21 AM by Hibernate Tools 3.2.0.b9
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.fireflow.engine.EngineException;
import org.fireflow.engine.IProcessInstance;
import org.fireflow.engine.IRuntimeContextAware;
import org.fireflow.engine.ITaskInstance;
import org.fireflow.engine.RuntimeContext;
import org.fireflow.engine.ou.IAssignable;
import org.fireflow.engine.persistence.IPersistenceService;
import org.fireflow.engine.IWorkItem;
import org.fireflow.engine.IWorkflowSession;
import org.fireflow.engine.IWorkflowSessionAware;
import org.fireflow.engine.definition.WorkflowDefinition;
import org.fireflow.engine.event.ITaskInstanceEventListener;
import org.fireflow.engine.event.TaskInstanceEvent;
import org.fireflow.engine.taskinstance.IApplicationHandler;
import org.fireflow.kenel.IActivityInstance;
import org.fireflow.kenel.INetInstance;
import org.fireflow.kenel.IToken;
import org.fireflow.kenel.KenelException;
import org.fireflow.model.DataField;
import org.fireflow.model.EventListener;
import org.fireflow.model.Task;
import org.fireflow.model.WorkflowProcess;
import org.fireflow.model.net.Activity;
import org.fireflow.model.reference.SubWorkflowProcess;

/**
 * TaskInstance generated by hbm2java
 */
public class TaskInstance implements ITaskInstance, IAssignable, IRuntimeContextAware,IWorkflowSessionAware, java.io.Serializable {

    private String id = null;
    private String taskId = null;
    private String activityId = null;
    private String name = null;
    private String displayName = null;
    private Integer state = null;
    private Date createdTime = null;
    private Date startedTime = null;
    private Date expiredTime = null;
    private Date endTime = null;
    private String completionStrategy = null;
    private IProcessInstance processInsatnce = null;
//	private Set workItems = new HashSet(0);
    private String taskType = null;

    protected RuntimeContext rtCtx = null;
    protected IWorkflowSession workflowSession = null;
    
    public void setRuntimeContext(RuntimeContext ctx){
        this.rtCtx = ctx;
    }    
    public RuntimeContext getRuntimeContext(){
        return this.rtCtx;
    }     
    public String getTaskType() {
        return taskType;
    }

    public void setTaskType(String taskType) {
        this.taskType = taskType;
    }

    public TaskInstance() {
    }

    public TaskInstance(ProcessInstance workflowProcessInsatnce) {
        this.processInsatnce = workflowProcessInsatnce;
    }

//	public TaskInstance(String taskId, String activityId, String name,
//			String displayName, Integer state, Date createdTime, Date startedTime,
//			Date expiredTime, Date endTime, Boolean asignToEveryone,
//			ProcessInstance workflowProcessInsatnceId, Set workItems) {
//		this.taskId = taskId;
//		this.activityId = activityId;
//		this.name = name;
//		this.label = displayName;
//		this.state = state;
//		this.createdTime = createdTime;
//		this.startedTime = startedTime;
//		this.expiredTime = expiredTime;
//		this.endTime = endTime;
//		this.asignToEveryone = asignToEveryone;
//		this.processInsatnce = workflowProcessInsatnceId;
//		this.workItems = workItems;
//	}
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTaskId() {
        return this.taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    public String getActivityId() {
        return this.activityId;
    }

    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDisplayName() {
        return this.displayName;
    }

    public void setDisplayName(String label) {
        this.displayName = label;
    }

    public Integer getState() {
        return this.state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Date getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    public Date getStartedTime() {
        return this.startedTime;
    }

    public void setStartedTime(Date startedTime) {
        this.startedTime = startedTime;
    }

    public Date getExpiredTime() {
        return this.expiredTime;
    }

    public void setExpiredTime(Date expiredTime) {
        this.expiredTime = expiredTime;
    }

    public Date getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public String getAssignmentStrategy() {
        return completionStrategy;
    }

    public void setAssignmentStrategy(String completionStrategy) {
        this.completionStrategy = completionStrategy;
    }

    public IProcessInstance getProcessInstance() {
        if (this.processInsatnce!=null){
            ((IRuntimeContextAware)this.processInsatnce).setRuntimeContext(rtCtx);
        }
        return this.processInsatnce;
    }

    public void setProcessInstance(
            IProcessInstance processInsatnce) {
        this.processInsatnce = processInsatnce;
    }

//	public Set getWorkItems() {
//		return this.workItems;
//	}
//
//	public void setWorkItems(Set workItems) {
//		this.workItems = workItems;
//	}
    public void asignToActor(String id)  throws EngineException,KenelException{
        this.asignToActor(id, true);
    }

    public void asignToActors(List<String> ids)  throws EngineException,KenelException{
        //task应该有一个标志(asignToEveryone)，表明asign的规则
        for (int i = 0; ids != null && i < ids.size(); i++) {
            createWorkItem(ids.get(i));
        }
    }

    protected IWorkItem createWorkItem(String actorId)  throws EngineException{
        IPersistenceService persistenceService = rtCtx.getPersistenceService();

        WorkItem wi = new WorkItem();
        wi.setTaskInstance(this);
        wi.setActorId(actorId);
        wi.setState(IWorkItem.INITIALIZED);
        wi.setCreatedTime(rtCtx.getCalendarService().getSysDate());
        wi.setRuntimeContext(rtCtx);
        persistenceService.saveOrUpdateWorkItem(wi);
        return wi;
//		this.getWorkItems().add(wi);
//		wi.setAsignToEveryone(asignToEveryone);
    //保存到数据库
    }
    
    public void complete()throws EngineException, KenelException {
        complete(null);
    }
    
    public void complete(IActivityInstance targetActivityInstance) throws EngineException, KenelException {

        IPersistenceService persistenceService = rtCtx.getPersistenceService();

        //第一步，首先结束当前taskInstance
        List<IWorkItem> workItemsList = persistenceService.findWorkItemsForTaskInstance(this.getId());
        boolean taskInstanceCanBeCompleted = true;
        for (int i = 0; workItemsList != null && i < workItemsList.size(); i++) {
            IWorkItem wi = workItemsList.get(i);
            if (wi.getState().intValue() == IWorkItem.INITIALIZED || wi.getState().intValue() == IWorkItem.STARTED) {
                taskInstanceCanBeCompleted = false;
                break;
            }
        }
        if (!taskInstanceCanBeCompleted) {
            return;
        }

        this.setState(ITaskInstance.COMPLETED);
        this.setEndTime(rtCtx.getCalendarService().getSysDate());
        persistenceService.saveOrUpdateTaskInstance(this);
        //触发相应的事件
        TaskInstanceEvent e = new TaskInstanceEvent();
        e.setEventType(TaskInstanceEvent.AFTER_TASK_INSTANCE_COMPLETE);
        this.fireTaskInstanceEvent(e);

        //第二步，尝试结束对应的activityInstance
        List<IToken> tokens = persistenceService.findTokensForProcessInstance(this.getProcessInstance().getId(), this.getActivityId());
        System.out.println("====Inside TaskInstance.complete():: " + (tokens == null ? "tokens is null" : ("tokens size is " + tokens.size())));
        if (tokens == null || tokens.size() == 0) {
            return;//表明activityInstance已经结束了。

        }
        if (tokens.size() > 1) {
            throw new EngineException("与activityId=" + this.getActivityId() + "对应的token数量(=" + tokens.size() + ")不正确，正确值能为1，因此无法完成complete操作");
        }
        IToken token = tokens.get(0);
        if (token.isAlive() == false) {
            throw new EngineException("与activityId=" + this.getActivityId() + "对应的token.alive=false，因此无法完成complete操作");
        }
        IProcessInstance processInstance = this.getProcessInstance();
        INetInstance netInstance = rtCtx.getKenelManager().getNetInstance(processInstance.getProcessId(), processInstance.getVersion());
        Object obj = netInstance.getWFElementInstance(this.getActivityId());
        if (obj == null) {
            throw new EngineException("系统没有找到与activityId=" + this.getActivityId() + "对应activityInstance，无法执行complete操作。");
        }

//		persistenceService.find
        

        List<ITaskInstance> taskInstanceList = persistenceService.findTaskInstancesForProcessInstance(this.getProcessInstance().getId(), this.getActivityId());

        boolean activityInstanceCanBeCompleted = true;
        WorkflowDefinition workflowDef = rtCtx.getDefinitionService().getWorkflowDefinitionByProcessIdAndVersion(processInstance.getProcessId(), processInstance.getVersion());
        WorkflowProcess workflowProcess = null;

        workflowProcess = workflowDef.getWorkflowProcess();


        Activity activity = (Activity) workflowProcess.findWFElementById(this.getActivityId());
//        System.out.println("++++++++++The completeStrategy is " + activity.getCompletionStrategy());
        if (activity.getCompletionStrategy().equals(Activity.ALL)) {
            for (int i = 0; taskInstanceList != null && i < taskInstanceList.size(); i++) {
                ITaskInstance taskInst = taskInstanceList.get(i);
                if (taskInst.getState().intValue() == ITaskInstance.INITIALIZED || taskInst.getState().intValue() == ITaskInstance.STARTED) {
                    activityInstanceCanBeCompleted = false;
                }
            }
        }

        if (!activityInstanceCanBeCompleted) {
            return;
        }


        ((IActivityInstance) obj).complete(token,targetActivityInstance);

    }

    public void start() throws EngineException, KenelException {
        //触发事件
        TaskInstanceEvent e = new TaskInstanceEvent();
        e.setEventType(TaskInstanceEvent.BEFORE_TASK_INSTANCE_START);
        this.fireTaskInstanceEvent(e);

        if (Task.FORM.equals(this.getTaskType())) {
            startManulTask();
        } else if (Task.TOOL.equals(this.getTaskType())) {
            startToolTask();
        } else if (Task.SUBFLOW.equals(this.getTaskType())) {
            startSubflowTask();
        } else {
            throw new EngineException("无法识别的TaskType值，taskType=" + this.getTaskType());
        }
    }

    protected void startManulTask() throws EngineException {
        if (this.getState().intValue() == ITaskInstance.INITIALIZED) {
            IPersistenceService persistenceService = rtCtx.getPersistenceService();

            this.setState(ITaskInstance.STARTED);
            this.setStartedTime(rtCtx.getCalendarService().getSysDate());
            persistenceService.saveOrUpdateTaskInstance(this);
            if (Task.ANY.equals(this.getAssignmentStrategy())) {
                persistenceService.deleteWorkItemsInInitializedState(this.getId());
                /*
                List<IWorkItem> workItemsList = persistenceService.findWorkItemsForTaskInstance(this.getId());
                for (int i = 0; workItemsList != null && i < workItemsList.size(); i++) {
                    WorkItem tmpWorkItem = (WorkItem) workItemsList.get(i);
                    if (tmpWorkItem.getState().intValue() == IWorkItem.INITIALIZED) {

                        tmpWorkItem.setState(IWorkItem.CANCELED);
                        tmpWorkItem.setEndTime(ctx.getCalendarService().getSysDate());
                        persistenceService.saveOrUpdateWorkItem(tmpWorkItem);
                    }
                }
                 */
            }
        }
    }

    protected void startToolTask() throws EngineException, KenelException {
        Task task = this.getTask();
        if (task == null) {
            throw new EngineException("The Task is null,can NOT start the taskinstance,");
        }
        if (task.getApplication() == null || task.getApplication().getHandler() == null) {
            throw new EngineException("The task.getApplication() is null or task.getApplication().getHandler() is null,can NOT start the taskinstance,");
        }
    
        Object obj = rtCtx.getBeanByClassName(task.getApplication().getHandler());

        try {
            ((IApplicationHandler) obj).execute(this);
        } catch (Exception e) {
            //TODO, 对tool类型的task抛出的错误应该怎么处理？
        }
        this.complete();

    }

    public Task getTask()  throws EngineException{
     
        IProcessInstance processInstance = this.getProcessInstance();
        WorkflowDefinition workflowDef = rtCtx.getDefinitionService().getWorkflowDefinitionByProcessIdAndVersion(processInstance.getProcessId(), processInstance.getVersion());
        if (workflowDef == null) {
            return null;
        }
        try {

            return (Task) workflowDef.getWorkflowProcess().findWFElementById(this.getTaskId());
        } catch (EngineException ex) {
            ex.printStackTrace();
            return null;
        }
    }

    public Activity getActivity() throws EngineException{

        IProcessInstance processInstance = this.getProcessInstance();
        WorkflowDefinition workflowDef = rtCtx.getDefinitionService().getWorkflowDefinitionByProcessIdAndVersion(processInstance.getProcessId(), processInstance.getVersion());
        if (workflowDef == null) {
            return null;
        }
        try {
            return (Activity) workflowDef.getWorkflowProcess().findWFElementById(this.getActivityId());
        } catch (EngineException ex) {
            ex.printStackTrace();
            return null;
        }
    }

    public WorkflowProcess getWorkflowProcess()  throws EngineException{
      
        IProcessInstance processInstance = this.getProcessInstance();
        WorkflowDefinition workflowDef = rtCtx.getDefinitionService().getWorkflowDefinitionByProcessIdAndVersion(processInstance.getProcessId(), processInstance.getVersion());
        if (workflowDef == null) {
            return null;
        }
        try {

            return workflowDef.getWorkflowProcess();
        } catch (EngineException ex) {
            Logger.getLogger(TaskInstance.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }

    }

    protected void startSubflowTask() throws EngineException, KenelException {
        Task task = this.getTask();
        SubWorkflowProcess subWorkflowProcess = task.getSubWorkflowProcess();
      
        WorkflowDefinition workflowDef = rtCtx.getDefinitionService().getTheLatestVersionOfWorkflowDefinition(subWorkflowProcess.getWorkflowProcessId());
        WorkflowProcess wfProcess = workflowDef.getWorkflowProcess();

        if (wfProcess == null) {
            throw new EngineException("系统中没有Id为" + subWorkflowProcess.getWorkflowProcessId() + "的流程定义");
        }

        ProcessInstance processInstance = new ProcessInstance();
        processInstance.setProcessId(wfProcess.getId());
        processInstance.setVersion(workflowDef.getVersion());
        processInstance.setDisplayName(wfProcess.getDisplayName());
        processInstance.setName(wfProcess.getName());
        processInstance.setState(IProcessInstance.INITIALIZED);

        //初始化流程变量,从父实例获得初始值
        Map processVars = this.getProcessInstance().getProcessInstanceVariables();
        List datafields = wfProcess.getDataFields();
        for (int i = 0; datafields != null && i < datafields.size(); i++) {
            DataField df = (DataField) datafields.get(i);
            if (df.getDataType().equals(DataField.STRING)) {
                if (processVars.get(df.getName()) != null && (processVars.get(df.getName()) instanceof String)) {
                    processInstance.setProcessInstanceVariable(df.getName(), processVars.get(df.getName()));
                } else if (df.getInitialValue() != null) {
                    processInstance.setProcessInstanceVariable(df.getName(), df.getInitialValue());
                } else {
                    processInstance.setProcessInstanceVariable(df.getName(), "");
                }
            } else if (df.getDataType().equals(DataField.INTEGER)) {
                if (processVars.get(df.getName()) != null && (processVars.get(df.getName()) instanceof Integer)) {
                    processInstance.setProcessInstanceVariable(df.getName(), processVars.get(df.getName()));
                } else if (df.getInitialValue() != null) {
                    try {
                        Integer intValue = new Integer(df.getInitialValue());
                        processInstance.setProcessInstanceVariable(df.getName(), intValue);
                    } catch (Exception e) {
                    }
                } else {
                    processInstance.setProcessInstanceVariable(df.getName(), new Integer(0));
                }
            } else if (df.getDataType().equals(DataField.FLOAT)) {
                if (processVars.get(df.getName()) != null && (processVars.get(df.getName()) instanceof Float)) {
                    processInstance.setProcessInstanceVariable(df.getName(), processVars.get(df.getName()));
                } else if (df.getInitialValue() != null) {
                    Float floatValue = new Float(df.getInitialValue());
                    processInstance.setProcessInstanceVariable(df.getName(), floatValue);
                } else {
                    processInstance.setProcessInstanceVariable(df.getName(), new Float(0));
                }
            } else if (df.getDataType().equals(DataField.BOOLEAN)) {
                if (processVars.get(df.getName()) != null && (processVars.get(df.getName()) instanceof Boolean)) {
                    processInstance.setProcessInstanceVariable(df.getName(), processVars.get(df.getName()));
                } else if (df.getInitialValue() != null) {
                    Boolean booleanValue = new Boolean(df.getInitialValue());
                    processInstance.setProcessInstanceVariable(df.getName(), booleanValue);
                } else {
                    processInstance.setProcessInstanceVariable(df.getName(), Boolean.FALSE);
                }
            } else if (df.getDataType().equals(DataField.DATETIME)) {
                //TODO 需要完善一下
            }
        }

        processInstance.setParentProcessInstanceId(this.getProcessInstance().getId());
        processInstance.setParentTaskInstanceId(this.getId());

        rtCtx.getPersistenceService().saveOrUpdateProcessInstance(processInstance);

        processInstance.run();
    }

    /**
     * 触发task instance相关的事件
     * @param e
     * @throws org.fireflow.engine.EngineException
     */
    protected void fireTaskInstanceEvent(TaskInstanceEvent e) throws EngineException {
        Task task = this.getTask();
        if (task == null) {
            return;
        }

        List listeners = task.getEventListeners();
        for (int i = 0; i < listeners.size(); i++) {
            EventListener listener = (EventListener) listeners.get(i);
            Object obj = rtCtx.getBeanByClassName(listener.getClassName());
            if (obj != null) {
                ((ITaskInstanceEventListener) obj).onTaskInstanceFired(e);
            }
        }
    }

    public void abort() throws EngineException, KenelException {
    }

    public void asignToActor(String id, boolean needSign) throws EngineException,KenelException {
        IWorkItem wi = createWorkItem(id);
        if (!needSign){
            wi.sign();
        }
    }
    
    public IWorkflowSession getCurrentWorkflowSession() {
        return this.workflowSession;
    }

    public void setCurrentWorkflowSession(IWorkflowSession session) {
        this.workflowSession = session;
    }    
}
