//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.261
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.60310.0
// 
namespace FireWorkflow.Net.Designer.DesignerServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessInstanceTrace", Namespace="http://schemas.datacontract.org/2004/07/FireWorkflow.Net.Engine.Impl")]
    public partial class ProcessInstanceTrace : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EdgeIdField;
        
        private string FromNodeIdField;
        
        private string ToNodeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EdgeId {
            get {
                return this.EdgeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EdgeIdField, value) != true)) {
                    this.EdgeIdField = value;
                    this.RaisePropertyChanged("EdgeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromNodeId {
            get {
                return this.FromNodeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FromNodeIdField, value) != true)) {
                    this.FromNodeIdField = value;
                    this.RaisePropertyChanged("FromNodeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToNodeId {
            get {
                return this.ToNodeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ToNodeIdField, value) != true)) {
                    this.ToNodeIdField = value;
                    this.RaisePropertyChanged("ToNodeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkflowDefinition", Namespace="http://schemas.datacontract.org/2004/07/FireWorkflow.Net.Engine.Definition")]
    public partial class WorkflowDefinition : FireWorkflow.Net.Designer.DesignerServiceReference.WorkflowDefinitionInfo {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkflowDefinitionInfo", Namespace="http://schemas.datacontract.org/2004/07/FireWorkflow.Net.Engine.Definition")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FireWorkflow.Net.Designer.DesignerServiceReference.WorkflowDefinition))]
    public partial class WorkflowDefinitionInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DefinitionTypeField;
        
        private string DescriptionField;
        
        private string DisplayNameField;
        
        private string IdField;
        
        private string NameField;
        
        private string ProcessIdField;
        
        private System.DateTime PublishTimeField;
        
        private string PublishUserField;
        
        private bool StateField;
        
        private System.DateTime UploadTimeField;
        
        private string UploadUserField;
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefinitionType {
            get {
                return this.DefinitionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DefinitionTypeField, value) != true)) {
                    this.DefinitionTypeField = value;
                    this.RaisePropertyChanged("DefinitionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessId {
            get {
                return this.ProcessIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessIdField, value) != true)) {
                    this.ProcessIdField = value;
                    this.RaisePropertyChanged("ProcessId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PublishTime {
            get {
                return this.PublishTimeField;
            }
            set {
                if ((this.PublishTimeField.Equals(value) != true)) {
                    this.PublishTimeField = value;
                    this.RaisePropertyChanged("PublishTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublishUser {
            get {
                return this.PublishUserField;
            }
            set {
                if ((object.ReferenceEquals(this.PublishUserField, value) != true)) {
                    this.PublishUserField = value;
                    this.RaisePropertyChanged("PublishUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UploadTime {
            get {
                return this.UploadTimeField;
            }
            set {
                if ((this.UploadTimeField.Equals(value) != true)) {
                    this.UploadTimeField = value;
                    this.RaisePropertyChanged("UploadTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UploadUser {
            get {
                return this.UploadUserField;
            }
            set {
                if ((object.ReferenceEquals(this.UploadUserField, value) != true)) {
                    this.UploadUserField = value;
                    this.RaisePropertyChanged("UploadUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Version {
            get {
                return this.VersionField;
            }
            set {
                if ((this.VersionField.Equals(value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DesignerServiceReference.IDesignerService")]
    public interface IDesignerService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDesignerService/GetWorkflowProcessXml", ReplyAction="http://tempuri.org/IDesignerService/GetWorkflowProcessXmlResponse")]
        System.IAsyncResult BeginGetWorkflowProcessXml(string id, System.AsyncCallback callback, object asyncState);
        
        string EndGetWorkflowProcessXml(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDesignerService/GetWorkflowProcessXmlProcessIdOrVersion", ReplyAction="http://tempuri.org/IDesignerService/GetWorkflowProcessXmlProcessIdOrVersionRespon" +
            "se")]
        System.IAsyncResult BeginGetWorkflowProcessXmlProcessIdOrVersion(string processID, int version, System.AsyncCallback callback, object asyncState);
        
        string EndGetWorkflowProcessXmlProcessIdOrVersion(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDesignerService/GetProcessInstanceTraceXml", ReplyAction="http://tempuri.org/IDesignerService/GetProcessInstanceTraceXmlResponse")]
        System.IAsyncResult BeginGetProcessInstanceTraceXml(string processInstanceId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<FireWorkflow.Net.Designer.DesignerServiceReference.ProcessInstanceTrace> EndGetProcessInstanceTraceXml(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDesignerService/GetAllLatestVersionsOfWorkflowDefinition", ReplyAction="http://tempuri.org/IDesignerService/GetAllLatestVersionsOfWorkflowDefinitionRespo" +
            "nse")]
        System.IAsyncResult BeginGetAllLatestVersionsOfWorkflowDefinition(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<FireWorkflow.Net.Designer.DesignerServiceReference.WorkflowDefinition> EndGetAllLatestVersionsOfWorkflowDefinition(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDesignerService/SaveOrUpdateWorkflowProcess", ReplyAction="http://tempuri.org/IDesignerService/SaveOrUpdateWorkflowProcessResponse")]
        System.IAsyncResult BeginSaveOrUpdateWorkflowProcess(string workflowProcessXml, int version, bool isState, System.AsyncCallback callback, object asyncState);
        
        bool EndSaveOrUpdateWorkflowProcess(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDesignerServiceChannel : FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWorkflowProcessXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWorkflowProcessXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWorkflowProcessXmlProcessIdOrVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWorkflowProcessXmlProcessIdOrVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProcessInstanceTraceXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProcessInstanceTraceXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<FireWorkflow.Net.Designer.DesignerServiceReference.ProcessInstanceTrace> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<FireWorkflow.Net.Designer.DesignerServiceReference.ProcessInstanceTrace>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllLatestVersionsOfWorkflowDefinitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllLatestVersionsOfWorkflowDefinitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<FireWorkflow.Net.Designer.DesignerServiceReference.WorkflowDefinition> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<FireWorkflow.Net.Designer.DesignerServiceReference.WorkflowDefinition>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveOrUpdateWorkflowProcessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveOrUpdateWorkflowProcessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DesignerServiceClient : System.ServiceModel.ClientBase<FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService>, FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService {
        
        private BeginOperationDelegate onBeginGetWorkflowProcessXmlDelegate;
        
        private EndOperationDelegate onEndGetWorkflowProcessXmlDelegate;
        
        private System.Threading.SendOrPostCallback onGetWorkflowProcessXmlCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetWorkflowProcessXmlProcessIdOrVersionDelegate;
        
        private EndOperationDelegate onEndGetWorkflowProcessXmlProcessIdOrVersionDelegate;
        
        private System.Threading.SendOrPostCallback onGetWorkflowProcessXmlProcessIdOrVersionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetProcessInstanceTraceXmlDelegate;
        
        private EndOperationDelegate onEndGetProcessInstanceTraceXmlDelegate;
        
        private System.Threading.SendOrPostCallback onGetProcessInstanceTraceXmlCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllLatestVersionsOfWorkflowDefinitionDelegate;
        
        private EndOperationDelegate onEndGetAllLatestVersionsOfWorkflowDefinitionDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllLatestVersionsOfWorkflowDefinitionCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveOrUpdateWorkflowProcessDelegate;
        
        private EndOperationDelegate onEndSaveOrUpdateWorkflowProcessDelegate;
        
        private System.Threading.SendOrPostCallback onSaveOrUpdateWorkflowProcessCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public DesignerServiceClient() {
        }
        
        public DesignerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DesignerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DesignerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DesignerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("无法设置 CookieContainer。请确保绑定包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<GetWorkflowProcessXmlCompletedEventArgs> GetWorkflowProcessXmlCompleted;
        
        public event System.EventHandler<GetWorkflowProcessXmlProcessIdOrVersionCompletedEventArgs> GetWorkflowProcessXmlProcessIdOrVersionCompleted;
        
        public event System.EventHandler<GetProcessInstanceTraceXmlCompletedEventArgs> GetProcessInstanceTraceXmlCompleted;
        
        public event System.EventHandler<GetAllLatestVersionsOfWorkflowDefinitionCompletedEventArgs> GetAllLatestVersionsOfWorkflowDefinitionCompleted;
        
        public event System.EventHandler<SaveOrUpdateWorkflowProcessCompletedEventArgs> SaveOrUpdateWorkflowProcessCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService.BeginGetWorkflowProcessXml(string id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWorkflowProcessXml(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService.EndGetWorkflowProcessXml(System.IAsyncResult result) {
            return base.Channel.EndGetWorkflowProcessXml(result);
        }
        
        private System.IAsyncResult OnBeginGetWorkflowProcessXml(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string id = ((string)(inValues[0]));
            return ((FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService)(this)).BeginGetWorkflowProcessXml(id, callback, asyncState);
        }
        
        private object[] OnEndGetWorkflowProcessXml(System.IAsyncResult result) {
            string retVal = ((FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService)(this)).EndGetWorkflowProcessXml(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWorkflowProcessXmlCompleted(object state) {
            if ((this.GetWorkflowProcessXmlCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWorkflowProcessXmlCompleted(this, new GetWorkflowProcessXmlCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWorkflowProcessXmlAsync(string id) {
            this.GetWorkflowProcessXmlAsync(id, null);
        }
        
        public void GetWorkflowProcessXmlAsync(string id, object userState) {
            if ((this.onBeginGetWorkflowProcessXmlDelegate == null)) {
                this.onBeginGetWorkflowProcessXmlDelegate = new BeginOperationDelegate(this.OnBeginGetWorkflowProcessXml);
            }
            if ((this.onEndGetWorkflowProcessXmlDelegate == null)) {
                this.onEndGetWorkflowProcessXmlDelegate = new EndOperationDelegate(this.OnEndGetWorkflowProcessXml);
            }
            if ((this.onGetWorkflowProcessXmlCompletedDelegate == null)) {
                this.onGetWorkflowProcessXmlCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWorkflowProcessXmlCompleted);
            }
            base.InvokeAsync(this.onBeginGetWorkflowProcessXmlDelegate, new object[] {
                        id}, this.onEndGetWorkflowProcessXmlDelegate, this.onGetWorkflowProcessXmlCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService.BeginGetWorkflowProcessXmlProcessIdOrVersion(string processID, int version, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWorkflowProcessXmlProcessIdOrVersion(processID, version, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService.EndGetWorkflowProcessXmlProcessIdOrVersion(System.IAsyncResult result) {
            return base.Channel.EndGetWorkflowProcessXmlProcessIdOrVersion(result);
        }
        
        private System.IAsyncResult OnBeginGetWorkflowProcessXmlProcessIdOrVersion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string processID = ((string)(inValues[0]));
            int version = ((int)(inValues[1]));
            return ((FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService)(this)).BeginGetWorkflowProcessXmlProcessIdOrVersion(processID, version, callback, asyncState);
        }
        
        private object[] OnEndGetWorkflowProcessXmlProcessIdOrVersion(System.IAsyncResult result) {
            string retVal = ((FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService)(this)).EndGetWorkflowProcessXmlProcessIdOrVersion(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWorkflowProcessXmlProcessIdOrVersionCompleted(object state) {
            if ((this.GetWorkflowProcessXmlProcessIdOrVersionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWorkflowProcessXmlProcessIdOrVersionCompleted(this, new GetWorkflowProcessXmlProcessIdOrVersionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWorkflowProcessXmlProcessIdOrVersionAsync(string processID, int version) {
            this.GetWorkflowProcessXmlProcessIdOrVersionAsync(processID, version, null);
        }
        
        public void GetWorkflowProcessXmlProcessIdOrVersionAsync(string processID, int version, object userState) {
            if ((this.onBeginGetWorkflowProcessXmlProcessIdOrVersionDelegate == null)) {
                this.onBeginGetWorkflowProcessXmlProcessIdOrVersionDelegate = new BeginOperationDelegate(this.OnBeginGetWorkflowProcessXmlProcessIdOrVersion);
            }
            if ((this.onEndGetWorkflowProcessXmlProcessIdOrVersionDelegate == null)) {
                this.onEndGetWorkflowProcessXmlProcessIdOrVersionDelegate = new EndOperationDelegate(this.OnEndGetWorkflowProcessXmlProcessIdOrVersion);
            }
            if ((this.onGetWorkflowProcessXmlProcessIdOrVersionCompletedDelegate == null)) {
                this.onGetWorkflowProcessXmlProcessIdOrVersionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWorkflowProcessXmlProcessIdOrVersionCompleted);
            }
            base.InvokeAsync(this.onBeginGetWorkflowProcessXmlProcessIdOrVersionDelegate, new object[] {
                        processID,
                        version}, this.onEndGetWorkflowProcessXmlProcessIdOrVersionDelegate, this.onGetWorkflowProcessXmlProcessIdOrVersionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService.BeginGetProcessInstanceTraceXml(string processInstanceId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProcessInstanceTraceXml(processInstanceId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<FireWorkflow.Net.Designer.DesignerServiceReference.ProcessInstanceTrace> FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService.EndGetProcessInstanceTraceXml(System.IAsyncResult result) {
            return base.Channel.EndGetProcessInstanceTraceXml(result);
        }
        
        private System.IAsyncResult OnBeginGetProcessInstanceTraceXml(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string processInstanceId = ((string)(inValues[0]));
            return ((FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService)(this)).BeginGetProcessInstanceTraceXml(processInstanceId, callback, asyncState);
        }
        
        private object[] OnEndGetProcessInstanceTraceXml(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<FireWorkflow.Net.Designer.DesignerServiceReference.ProcessInstanceTrace> retVal = ((FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService)(this)).EndGetProcessInstanceTraceXml(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProcessInstanceTraceXmlCompleted(object state) {
            if ((this.GetProcessInstanceTraceXmlCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProcessInstanceTraceXmlCompleted(this, new GetProcessInstanceTraceXmlCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProcessInstanceTraceXmlAsync(string processInstanceId) {
            this.GetProcessInstanceTraceXmlAsync(processInstanceId, null);
        }
        
        public void GetProcessInstanceTraceXmlAsync(string processInstanceId, object userState) {
            if ((this.onBeginGetProcessInstanceTraceXmlDelegate == null)) {
                this.onBeginGetProcessInstanceTraceXmlDelegate = new BeginOperationDelegate(this.OnBeginGetProcessInstanceTraceXml);
            }
            if ((this.onEndGetProcessInstanceTraceXmlDelegate == null)) {
                this.onEndGetProcessInstanceTraceXmlDelegate = new EndOperationDelegate(this.OnEndGetProcessInstanceTraceXml);
            }
            if ((this.onGetProcessInstanceTraceXmlCompletedDelegate == null)) {
                this.onGetProcessInstanceTraceXmlCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProcessInstanceTraceXmlCompleted);
            }
            base.InvokeAsync(this.onBeginGetProcessInstanceTraceXmlDelegate, new object[] {
                        processInstanceId}, this.onEndGetProcessInstanceTraceXmlDelegate, this.onGetProcessInstanceTraceXmlCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService.BeginGetAllLatestVersionsOfWorkflowDefinition(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllLatestVersionsOfWorkflowDefinition(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<FireWorkflow.Net.Designer.DesignerServiceReference.WorkflowDefinition> FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService.EndGetAllLatestVersionsOfWorkflowDefinition(System.IAsyncResult result) {
            return base.Channel.EndGetAllLatestVersionsOfWorkflowDefinition(result);
        }
        
        private System.IAsyncResult OnBeginGetAllLatestVersionsOfWorkflowDefinition(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService)(this)).BeginGetAllLatestVersionsOfWorkflowDefinition(callback, asyncState);
        }
        
        private object[] OnEndGetAllLatestVersionsOfWorkflowDefinition(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<FireWorkflow.Net.Designer.DesignerServiceReference.WorkflowDefinition> retVal = ((FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService)(this)).EndGetAllLatestVersionsOfWorkflowDefinition(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllLatestVersionsOfWorkflowDefinitionCompleted(object state) {
            if ((this.GetAllLatestVersionsOfWorkflowDefinitionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllLatestVersionsOfWorkflowDefinitionCompleted(this, new GetAllLatestVersionsOfWorkflowDefinitionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllLatestVersionsOfWorkflowDefinitionAsync() {
            this.GetAllLatestVersionsOfWorkflowDefinitionAsync(null);
        }
        
        public void GetAllLatestVersionsOfWorkflowDefinitionAsync(object userState) {
            if ((this.onBeginGetAllLatestVersionsOfWorkflowDefinitionDelegate == null)) {
                this.onBeginGetAllLatestVersionsOfWorkflowDefinitionDelegate = new BeginOperationDelegate(this.OnBeginGetAllLatestVersionsOfWorkflowDefinition);
            }
            if ((this.onEndGetAllLatestVersionsOfWorkflowDefinitionDelegate == null)) {
                this.onEndGetAllLatestVersionsOfWorkflowDefinitionDelegate = new EndOperationDelegate(this.OnEndGetAllLatestVersionsOfWorkflowDefinition);
            }
            if ((this.onGetAllLatestVersionsOfWorkflowDefinitionCompletedDelegate == null)) {
                this.onGetAllLatestVersionsOfWorkflowDefinitionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllLatestVersionsOfWorkflowDefinitionCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllLatestVersionsOfWorkflowDefinitionDelegate, null, this.onEndGetAllLatestVersionsOfWorkflowDefinitionDelegate, this.onGetAllLatestVersionsOfWorkflowDefinitionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService.BeginSaveOrUpdateWorkflowProcess(string workflowProcessXml, int version, bool isState, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveOrUpdateWorkflowProcess(workflowProcessXml, version, isState, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService.EndSaveOrUpdateWorkflowProcess(System.IAsyncResult result) {
            return base.Channel.EndSaveOrUpdateWorkflowProcess(result);
        }
        
        private System.IAsyncResult OnBeginSaveOrUpdateWorkflowProcess(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string workflowProcessXml = ((string)(inValues[0]));
            int version = ((int)(inValues[1]));
            bool isState = ((bool)(inValues[2]));
            return ((FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService)(this)).BeginSaveOrUpdateWorkflowProcess(workflowProcessXml, version, isState, callback, asyncState);
        }
        
        private object[] OnEndSaveOrUpdateWorkflowProcess(System.IAsyncResult result) {
            bool retVal = ((FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService)(this)).EndSaveOrUpdateWorkflowProcess(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveOrUpdateWorkflowProcessCompleted(object state) {
            if ((this.SaveOrUpdateWorkflowProcessCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveOrUpdateWorkflowProcessCompleted(this, new SaveOrUpdateWorkflowProcessCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveOrUpdateWorkflowProcessAsync(string workflowProcessXml, int version, bool isState) {
            this.SaveOrUpdateWorkflowProcessAsync(workflowProcessXml, version, isState, null);
        }
        
        public void SaveOrUpdateWorkflowProcessAsync(string workflowProcessXml, int version, bool isState, object userState) {
            if ((this.onBeginSaveOrUpdateWorkflowProcessDelegate == null)) {
                this.onBeginSaveOrUpdateWorkflowProcessDelegate = new BeginOperationDelegate(this.OnBeginSaveOrUpdateWorkflowProcess);
            }
            if ((this.onEndSaveOrUpdateWorkflowProcessDelegate == null)) {
                this.onEndSaveOrUpdateWorkflowProcessDelegate = new EndOperationDelegate(this.OnEndSaveOrUpdateWorkflowProcess);
            }
            if ((this.onSaveOrUpdateWorkflowProcessCompletedDelegate == null)) {
                this.onSaveOrUpdateWorkflowProcessCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveOrUpdateWorkflowProcessCompleted);
            }
            base.InvokeAsync(this.onBeginSaveOrUpdateWorkflowProcessDelegate, new object[] {
                        workflowProcessXml,
                        version,
                        isState}, this.onEndSaveOrUpdateWorkflowProcessDelegate, this.onSaveOrUpdateWorkflowProcessCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService CreateChannel() {
            return new DesignerServiceClientChannel(this);
        }
        
        private class DesignerServiceClientChannel : ChannelBase<FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService>, FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService {
            
            public DesignerServiceClientChannel(System.ServiceModel.ClientBase<FireWorkflow.Net.Designer.DesignerServiceReference.IDesignerService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetWorkflowProcessXml(string id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("GetWorkflowProcessXml", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetWorkflowProcessXml(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetWorkflowProcessXml", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetWorkflowProcessXmlProcessIdOrVersion(string processID, int version, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = processID;
                _args[1] = version;
                System.IAsyncResult _result = base.BeginInvoke("GetWorkflowProcessXmlProcessIdOrVersion", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetWorkflowProcessXmlProcessIdOrVersion(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetWorkflowProcessXmlProcessIdOrVersion", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetProcessInstanceTraceXml(string processInstanceId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = processInstanceId;
                System.IAsyncResult _result = base.BeginInvoke("GetProcessInstanceTraceXml", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<FireWorkflow.Net.Designer.DesignerServiceReference.ProcessInstanceTrace> EndGetProcessInstanceTraceXml(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<FireWorkflow.Net.Designer.DesignerServiceReference.ProcessInstanceTrace> _result = ((System.Collections.ObjectModel.ObservableCollection<FireWorkflow.Net.Designer.DesignerServiceReference.ProcessInstanceTrace>)(base.EndInvoke("GetProcessInstanceTraceXml", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllLatestVersionsOfWorkflowDefinition(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllLatestVersionsOfWorkflowDefinition", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<FireWorkflow.Net.Designer.DesignerServiceReference.WorkflowDefinition> EndGetAllLatestVersionsOfWorkflowDefinition(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<FireWorkflow.Net.Designer.DesignerServiceReference.WorkflowDefinition> _result = ((System.Collections.ObjectModel.ObservableCollection<FireWorkflow.Net.Designer.DesignerServiceReference.WorkflowDefinition>)(base.EndInvoke("GetAllLatestVersionsOfWorkflowDefinition", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveOrUpdateWorkflowProcess(string workflowProcessXml, int version, bool isState, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = workflowProcessXml;
                _args[1] = version;
                _args[2] = isState;
                System.IAsyncResult _result = base.BeginInvoke("SaveOrUpdateWorkflowProcess", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndSaveOrUpdateWorkflowProcess(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("SaveOrUpdateWorkflowProcess", _args, result)));
                return _result;
            }
        }
    }
}
