using System;
using System.Collections.Generic;
using System.Text;
using ISM.FireWorkflow.Engine;
using ISM.FireWorkflow.Engine.Definition;
using ISM.FireWorkflow.Engine.Persistence;
using ISM.FireWorkflow.Engine.Taskinstance;
using ISM.FireWorkflow.Model;
using ISM.FireWorkflow.Model.Net;
using ISM.FireWorkflow.Kernel;

namespace ISM.FireWorkflow.Engine.Impl
{
    /**
 * TaskInstance generated by hbm2java
 */
    [Serializable]
    public class TaskInstance : ITaskInstance, IAssignable, IRuntimeContextAware, IWorkflowSessionAware
    {

        private String id = null;
        private String taskId = null;
        private String activityId = null;
        private String name = null;
        private String displayName = null;
        private Int32? state = null;
        private Boolean? suspended = null;
        private DateTime? createdTime = null;
        private DateTime? startedTime = null;
        private DateTime? expiredTime = null;
        private DateTime? endTime = null;
        private String assignmentStrategy = null;
        private String processInstanceId = null;
        private String processId = null;
        private Int32 version ;
        //	private Set workItems = new HashSet(0);
        private String taskType = null;
        private String targetActivityId = null;
        private String fromActivityId = null;
        //    private String tokenId = null;
        private Int32 stepNumber ;

        private Boolean canBeWithdrawn = true;

        [NonSerialized]
        protected RuntimeContext rtCtx = null;

        [NonSerialized]
        protected IWorkflowSession workflowSession = null;

        [NonSerialized]
        private IProcessInstance processInsatance = null;

        public void setRuntimeContext(RuntimeContext ctx)
        {
            this.rtCtx = ctx;
        }

        public RuntimeContext getRuntimeContext()
        {
            return this.rtCtx;
        }

        public override String getTaskType()
        {
            return taskType;
        }

        public void setTaskType(String taskType)
        {
            this.taskType = taskType;
        }

        public TaskInstance()
        {
            this.state = ITaskInstance.INITIALIZED;
            this.suspended = false;
        }

        public TaskInstance(ProcessInstance workflowProcessInsatnce)
        {
            this.state = ITaskInstance.INITIALIZED;
            this.suspended = false;
            this.processInsatance = workflowProcessInsatnce;
        }

        //	public TaskInstance(String taskId, String activityId, String name,
        //			String displayName, Int32 state, DateTime createdTime, DateTime startedTime,
        //			DateTime expiredTime, DateTime endTime, Boolean asignToEveryone,
        //			ProcessInstance workflowProcessInsatnceId, Set workItems) {
        //		this.taskId = taskId;
        //		this.activityId = activityId;
        //		this.name = name;
        //		this.label = displayName;
        //		this.state = state;
        //		this.createdTime = createdTime;
        //		this.startedTime = startedTime;
        //		this.expiredTime = expiredTime;
        //		this.endTime = endTime;
        //		this.asignToEveryone = asignToEveryone;
        //		this.processInsatnce = workflowProcessInsatnceId;
        //		this.workItems = workItems;
        //	}
        public override String getId()
        {
            return this.id;
        }

        public void setId(String id)
        {
            this.id = id;
        }

        public override String getTaskId()
        {
            return this.taskId;
        }

        public void setTaskId(String taskId)
        {
            this.taskId = taskId;
        }

        public override String getActivityId()
        {
            return this.activityId;
        }

        public void setActivityId(String activityId)
        {
            this.activityId = activityId;
        }

        public override String getName()
        {
            return this.name;
        }

        public void setName(String name)
        {
            this.name = name;
        }

        public override String getDisplayName()
        {
            return this.displayName;
        }

        public void setDisplayName(String label)
        {
            this.displayName = label;
        }

        public override Int32? getState()
        {
            return this.state;
        }

        public void setState(Int32 state)
        {
            this.state = state;
        }

        public override DateTime? getCreatedTime()
        {
            return this.createdTime;
        }

        public void setCreatedTime(DateTime createdTime)
        {
            this.createdTime = createdTime;
        }

        public override DateTime? getStartedTime()
        {
            return this.startedTime;
        }

        public void setStartedTime(DateTime startedTime)
        {
            this.startedTime = startedTime;
        }

        public override DateTime? getExpiredTime()
        {
            return this.expiredTime;
        }

        public void setExpiredTime(DateTime expiredTime)
        {
            this.expiredTime = expiredTime;
        }

        public override DateTime? getEndTime()
        {
            return this.endTime;
        }

        public void setEndTime(DateTime endTime)
        {
            this.endTime = endTime;
        }

        public override String getAssignmentStrategy()
        {
            return assignmentStrategy;
        }

        public void setAssignmentStrategy(String completionStrategy)
        {
            this.assignmentStrategy = completionStrategy;
        }

        public override Boolean? isSuspended()
        {
            return suspended;
        }

        public Boolean? getSuspended()
        {
            return suspended;
        }
        public void setSuspended(Boolean suspended)
        {
            this.suspended = suspended;
        }




        public IProcessInstance getAliveProcessInstance()
        {
            if (this.processInsatance == null)
            {
                if (this.rtCtx != null)
                {
                    IPersistenceService persistenceService = rtCtx.getPersistenceService();
                    this.processInsatance = persistenceService.findAliveProcessInstanceById(this.processInstanceId);
                }
            }
            if (this.processInsatance != null)
            {
                if (this.workflowSession != null)
                {
                    ((IWorkflowSessionAware)this.processInsatance).setCurrentWorkflowSession(this.workflowSession);
                }
                if (this.rtCtx != null)
                {
                    ((IRuntimeContextAware)this.processInsatance).setRuntimeContext(this.rtCtx);
                }

            }
            return this.processInsatance;
        }

        /*
        public void setProcessInstance(
        IProcessInstance processInsatnce) {
        this.processInsatnce = processInsatnce;
        if (this.processInsatnce!=null ){
        this.processInstanceId = this.processInsatnce.getId();
        }else {
        this.processInstanceId = null;
        }
        }
         */
        //	public Set getWorkItems() {
        //		return this.workItems;
        //	}
        //
        //	public void setWorkItems(Set workItems) {
        //		this.workItems = workItems;
        //	}
        public IWorkItem asignToActor(String id)// throws EngineException, KernelException 
        {
            ITaskInstanceManager taskInstanceMgr = this.rtCtx.getTaskInstanceManager();
            WorkItem wi = taskInstanceMgr.createWorkItem(this.workflowSession, this.getAliveProcessInstance(), this, id);
            return wi;
        }

        public List<IWorkItem> asignToActors(List<String> ids)// throws EngineException, KernelException 
        {
            //task应该有一个标志(asignToEveryone)，表明asign的规则
            List<IWorkItem> workItemList = new List<IWorkItem>();
            for (int i = 0; ids != null && i < ids.Count; i++)
            {
                ITaskInstanceManager taskInstanceMgr = this.rtCtx.getTaskInstanceManager();
                WorkItem wi = taskInstanceMgr.createWorkItem(this.workflowSession, this.getAliveProcessInstance(), this, ids[i]);
                wi.setCurrentWorkflowSession(workflowSession);
                workItemList.Add(wi);
            }
            return workItemList;
        }

        public override Task getTask()// throws EngineException 
        {
            if (rtCtx == null) return null; //System.out.println("====Inside taskInstance rtCtx is null");
            IDefinitionService definitionService = rtCtx.getDefinitionService();
            if (definitionService == null) return null;//System.out.println("====Inside taskInstance definitionService is null");
            WorkflowDefinition workflowDef = definitionService.getWorkflowDefinitionByProcessIdAndVersionNumber(this.getProcessId(), this.getVersion());
            if (workflowDef == null)
            {
                return null;
            }

            return (Task)workflowDef.getWorkflowProcess().findWFElementById(this.getTaskId());

        }

        public override Activity getActivity()
        {
            WorkflowDefinition workflowDef = rtCtx.getDefinitionService().getWorkflowDefinitionByProcessIdAndVersionNumber(this.getProcessId(), this.getVersion());
            if (workflowDef == null)
            {
                return null;
            }
            return (Activity)workflowDef.getWorkflowProcess().findWFElementById(this.getActivityId());
        }

        public override WorkflowProcess getWorkflowProcess()
        {
            WorkflowDefinition workflowDef = rtCtx.getDefinitionService().getWorkflowDefinitionByProcessIdAndVersionNumber(this.getProcessId(), this.getVersion());
            if (workflowDef == null)
            {
                return null;
            }

            return workflowDef.getWorkflowProcess();
        }

        public /*final*/ void start()
        {
            ITaskInstanceManager taskInstanceMgr = this.rtCtx.getTaskInstanceManager();
            taskInstanceMgr.startTaskInstance(workflowSession, this.getAliveProcessInstance(), this);
            //        taskInstanceMgr.startTaskInstance(this);
        }

        public void complete(IActivityInstance targetActivityInstance)
        {
            ITaskInstanceManager taskInstanceMgr = this.rtCtx.getTaskInstanceManager();
            taskInstanceMgr.completeTaskInstance(workflowSession, this.getAliveProcessInstance(), this, targetActivityInstance);
            //        taskInstanceMgr.completeTaskInstance(this, targetActivityInstance);
        }

        /*
            public IWorkItem asignToActor(String id, Boolean needClaim) throws EngineException, KernelException {
                ITaskInstanceManager taskInstanceMgr = this.rtCtx.getTaskInstanceManager();
                WorkItem wi = taskInstanceMgr.createWorkItem(this, id);
                if (!needClaim) {
                    wi.claim();
                }
                return wi;
            }
        */
        public IWorkflowSession getCurrentWorkflowSession()
        {
            return this.workflowSession;
        }

        public void setCurrentWorkflowSession(IWorkflowSession session)
        {
            this.workflowSession = session;
        }

        public override String getProcessInstanceId()
        {
            return this.processInstanceId;
        }

        public void setProcessInstanceId(String s)
        {
            this.processInstanceId = s;
        }

        public override String getProcessId()
        {
            return this.processId;
        }

        public void setProcessId(String s)
        {
            this.processId = s;
        }

        public override Int32 getVersion()
        {
            return this.version;
        }

        public void setVersion(Int32 v)
        {
            this.version = v;
        }

        public override String getTargetActivityId()
        {
            return this.targetActivityId;
        }

        public void setTargetActivityId(String s)
        {
            this.targetActivityId = s;
        }

        public override Int32 getStepNumber()
        {
            return this.stepNumber;
        }

        public void setStepNumber(Int32 i)
        {
            this.stepNumber = i;
        }

        public Boolean getCanBeWithdrawn()
        {
            return canBeWithdrawn;
        }

        public void setCanBeWithdrawn(Boolean canBeWithdrawn)
        {
            this.canBeWithdrawn = canBeWithdrawn;
        }

        public String getFromActivityId()
        {
            return fromActivityId;
        }

        public void setFromActivityId(String fromActivityId)
        {
            this.fromActivityId = fromActivityId;
        }

        public override void suspend()
        {
            if (this.state == ITaskInstance.COMPLETED || this.state == ITaskInstance.CANCELED)
            {
                throw new EngineException(this.getAliveProcessInstance(), this.getTask(), "The task instance can not be suspended,the state of this task instance is " + this.state);
            }
            if (this.isSuspended() != null && (Boolean)this.isSuspended())
            {
                return;
            }
            this.setSuspended(true);
            IPersistenceService persistenceService = this.rtCtx.getPersistenceService();
            persistenceService.saveOrUpdateTaskInstance(this);
        }

        public override void restore()
        {
            if (this.state == ITaskInstance.COMPLETED || this.state == ITaskInstance.CANCELED)
            {
                throw new EngineException(this.getAliveProcessInstance(), this.getTask(), "The task instance can not be restored,the state of this task instance is " + this.state);
            }
            if (!(this.isSuspended() != null && (Boolean)this.isSuspended()))
            {
                return;
            }
            this.setSuspended(false);
            IPersistenceService persistenceService = this.rtCtx.getPersistenceService();
            persistenceService.saveOrUpdateTaskInstance(this);
        }


        //    public String getTokenId() {
        //        return tokenId;
        //    }
        //
        //    public void setTokenId(String tokenId) {
        //        this.tokenId = tokenId;
        //    }
    }
}
