alter table T_FF_RT_APPOINTED_TRANS_NAME drop foreign key FK8DB15AAAA40738D8;
alter table T_FF_RT_JOINPOINT drop foreign key FK86E693FD7AF471D8;
alter table T_FF_RT_PROCINST_VAR drop foreign key FKD79C420D7AF471D8;
alter table T_FF_RT_TASKINSTANCE drop foreign key FK866E74437AF471D8;
alter table T_FF_RT_TOKEN drop foreign key FKEE7A76D07AF471D8;
alter table T_FF_RT_WORKITEM drop foreign key FK4131554DE2527DDC;
drop table if exists T_FF_DF_WORKFLOWDEF;
drop table if exists T_FF_RT_APPOINTED_TRANS_NAME;
drop table if exists T_FF_RT_JOINPOINT;
drop table if exists T_FF_RT_PROCESSINSTANCE;
drop table if exists T_FF_RT_PROCINST_VAR;
drop table if exists T_FF_RT_TASKINSTANCE;
drop table if exists T_FF_RT_TOKEN;
drop table if exists T_FF_RT_WORKITEM;
create table T_FF_DF_WORKFLOWDEF (ID varchar(50) not null, PROCESS_ID varchar(50) not null, NAME varchar(100) not null, DISPLAY_NAME varchar(128), DESCRIPTION text, VERSION integer not null, PROCESS_CONTENT text, PUBLISHED bit, PUBLISHER varchar(50), PUBLISH_TIME datetime, primary key (ID));
create table T_FF_RT_APPOINTED_TRANS_NAME (JOINPOINT_ID varchar(50) not null, TRANSITION_NAME varchar(255) not null, primary key (JOINPOINT_ID, TRANSITION_NAME));
create table T_FF_RT_JOINPOINT (ID varchar(50) not null, SYNCHRONIZER_ID varchar(50) not null, VALUE integer, ALIVE bit, PROCESSINSTANCE_ID varchar(50) not null, primary key (ID));
create table T_FF_RT_PROCESSINSTANCE (ID varchar(50) not null, PROCESS_ID varchar(50) not null, VERSION integer not null, NAME varchar(100), DISPLAY_NAME varchar(128), STATE integer, CREATED_TIME datetime, STARTED_TIME datetime, EXPIRED_TIME datetime, PARENT_PROCESSINSTANCE_ID varchar(255), PARENT_TASKINSTANCE_ID varchar(255), primary key (ID));
create table T_FF_RT_PROCINST_VAR (PROCESSINSTANCE_ID varchar(50) not null, VALUE varchar(255), NAME varchar(255) not null, primary key (PROCESSINSTANCE_ID, NAME));
create table T_FF_RT_TASKINSTANCE (ID varchar(50) not null, BIZ_TYPE varchar(50) not null, TASK_ID varchar(50) not null, ACTIVITY_ID varchar(50) not null, NAME varchar(50) not null, DISPLAY_NAME varchar(128), STATE integer, TASK_TYPE varchar(15), CREATED_TIME datetime not null, STARTED_TIME datetime, EXPIRED_TIME datetime, END_TIME datetime, COMPLETION_STRATEGY varchar(255) not null, PROCESSINSTANCE_ID varchar(50) not null, primary key (ID));
create table T_FF_RT_TOKEN (ID varchar(50) not null, ALIVE bit not null, VALUE integer not null, NODE_ID varchar(255) not null, PROCESSINSTANCE_ID varchar(50) not null, primary key (ID));
create table T_FF_RT_WORKITEM (ID varchar(50) not null, STATE integer not null, CREATED_TIME datetime not null, SIGNED_TIME datetime, END_TIME datetime, ACTOR_ID varchar(50), COMMENTS text, TASKINSTANCE_ID varchar(50) not null, primary key (ID));
alter table T_FF_RT_APPOINTED_TRANS_NAME add index FK8DB15AAAA40738D8 (JOINPOINT_ID), add constraint FK8DB15AAAA40738D8 foreign key (JOINPOINT_ID) references T_FF_RT_JOINPOINT (ID);
alter table T_FF_RT_JOINPOINT add index FK86E693FD7AF471D8 (PROCESSINSTANCE_ID), add constraint FK86E693FD7AF471D8 foreign key (PROCESSINSTANCE_ID) references T_FF_RT_PROCESSINSTANCE (ID);
alter table T_FF_RT_PROCINST_VAR add index FKD79C420D7AF471D8 (PROCESSINSTANCE_ID), add constraint FKD79C420D7AF471D8 foreign key (PROCESSINSTANCE_ID) references T_FF_RT_PROCESSINSTANCE (ID);
alter table T_FF_RT_TASKINSTANCE add index FK866E74437AF471D8 (PROCESSINSTANCE_ID), add constraint FK866E74437AF471D8 foreign key (PROCESSINSTANCE_ID) references T_FF_RT_PROCESSINSTANCE (ID);
alter table T_FF_RT_TOKEN add index FKEE7A76D07AF471D8 (PROCESSINSTANCE_ID), add constraint FKEE7A76D07AF471D8 foreign key (PROCESSINSTANCE_ID) references T_FF_RT_PROCESSINSTANCE (ID);
alter table T_FF_RT_WORKITEM add index FK4131554DE2527DDC (TASKINSTANCE_ID), add constraint FK4131554DE2527DDC foreign key (TASKINSTANCE_ID) references T_FF_RT_TASKINSTANCE (ID);
