drop table T_FF_DF_WORKFLOWDEF cascade constraints;
drop table T_FF_RT_APPOINTED_TRANS_NAME cascade constraints;
drop table T_FF_RT_JOINPOINT cascade constraints;
drop table T_FF_RT_PROCESSINSTANCE cascade constraints;
drop table T_FF_RT_PROCINST_VAR cascade constraints;
drop table T_FF_RT_TASKINSTANCE cascade constraints;
drop table T_FF_RT_TOKEN cascade constraints;
drop table T_FF_RT_WORKITEM cascade constraints;
create table T_FF_DF_WORKFLOWDEF (ID varchar2(50 char) not null, PROCESS_ID varchar2(50 char) not null, NAME varchar2(100 char) not null, DISPLAY_NAME varchar2(128 char), DESCRIPTION varchar2(1024 char), VERSION number(10,0) not null, PROCESS_CONTENT clob, PUBLISHED number(1,0), PUBLISHER varchar2(50 char), PUBLISH_TIME timestamp, primary key (ID));
create table T_FF_RT_APPOINTED_TRANS_NAME (JOINPOINT_ID varchar2(50 char) not null, TRANSITION_NAME varchar2(255 char) not null, primary key (JOINPOINT_ID, TRANSITION_NAME));
create table T_FF_RT_JOINPOINT (ID varchar2(50 char) not null, SYNCHRONIZER_ID varchar2(50 char) not null, VALUE number(10,0), ALIVE number(1,0), PROCESSINSTANCE_ID varchar2(50 char) not null, primary key (ID));
create table T_FF_RT_PROCESSINSTANCE (ID varchar2(50 char) not null, PROCESS_ID varchar2(50 char) not null, VERSION number(10,0) not null, NAME varchar2(100 char), DISPLAY_NAME varchar2(128 char), STATE number(10,0), CREATED_TIME timestamp, STARTED_TIME timestamp, EXPIRED_TIME timestamp, PARENT_PROCESSINSTANCE_ID varchar2(255 char), PARENT_TASKINSTANCE_ID varchar2(255 char), primary key (ID));
create table T_FF_RT_PROCINST_VAR (PROCESSINSTANCE_ID varchar2(50 char) not null, VALUE varchar2(255 char), NAME varchar2(255 char) not null, primary key (PROCESSINSTANCE_ID, NAME));
create table T_FF_RT_TASKINSTANCE (ID varchar2(50 char) not null, BIZ_TYPE varchar2(50 char) not null, TASK_ID varchar2(50 char) not null, ACTIVITY_ID varchar2(50 char) not null, NAME varchar2(50 char) not null, DISPLAY_NAME varchar2(128 char), STATE number(10,0), TASK_TYPE varchar2(15 char), CREATED_TIME timestamp not null, STARTED_TIME timestamp, EXPIRED_TIME timestamp, END_TIME timestamp, COMPLETION_STRATEGY varchar2(255 char) not null, PROCESSINSTANCE_ID varchar2(50 char) not null, primary key (ID));
create table T_FF_RT_TOKEN (ID varchar2(50 char) not null, ALIVE number(1,0) not null, VALUE number(10,0) not null, NODE_ID varchar2(255 char) not null, PROCESSINSTANCE_ID varchar2(50 char) not null, primary key (ID));
create table T_FF_RT_WORKITEM (ID varchar2(50 char) not null, STATE number(10,0) not null, CREATED_TIME timestamp not null, SIGNED_TIME timestamp, END_TIME timestamp, ACTOR_ID varchar2(50 char), COMMENTS varchar2(1024 char), TASKINSTANCE_ID varchar2(50 char) not null, primary key (ID));
alter table T_FF_RT_APPOINTED_TRANS_NAME add constraint FK8DB15AAAA40738D8 foreign key (JOINPOINT_ID) references T_FF_RT_JOINPOINT;
alter table T_FF_RT_JOINPOINT add constraint FK86E693FD7AF471D8 foreign key (PROCESSINSTANCE_ID) references T_FF_RT_PROCESSINSTANCE;
alter table T_FF_RT_PROCINST_VAR add constraint FKD79C420D7AF471D8 foreign key (PROCESSINSTANCE_ID) references T_FF_RT_PROCESSINSTANCE;
alter table T_FF_RT_TASKINSTANCE add constraint FK866E74437AF471D8 foreign key (PROCESSINSTANCE_ID) references T_FF_RT_PROCESSINSTANCE;
alter table T_FF_RT_TOKEN add constraint FKEE7A76D07AF471D8 foreign key (PROCESSINSTANCE_ID) references T_FF_RT_PROCESSINSTANCE;
alter table T_FF_RT_WORKITEM add constraint FK4131554DE2527DDC foreign key (TASKINSTANCE_ID) references T_FF_RT_TASKINSTANCE;
